on:
  - workflow_dispatch
  - push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Configure GitHub Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d
      - name: Set up Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3
      - name: Build files
        run: just b
      - name: Package files
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: ./
  deploy-pages:
    runs-on: macos-latest
    permissions:
      pages: write
      id-token: write
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
